### ISSUE TITLE
no intro text

### ISSUE THREAD

**Issue by Alittletrolling** [gedehari/Funkin-IzzyEngine#10]
bruh no funny words when i open the game like wtf man what are you doing and no gameplay bruh like wtf where is the gameplay bruh so far its just a OGG player like bruh wtf

**Comment by gedehari** [comment]
Forgot to implement this. Will be implemented later.

**Comment by Alittletrolling** [comment]
implement it now

**Comment by Alittletrolling** [comment]
https://tenor.com/view/troll-pilled-gif-19289988

**Comment by gedehari** [comment]
Added in 415d625c5fc40d299235bb03ab179e68a9924a11, closing
