### ISSUE TITLE
The Clone Wars

### ISSUE THREAD

**Issue by Alittletrolling** [gedehari/Funkin-IzzyEngine#12]
alright so in a galaxy far far away there was like this republic kind of thing what would democracy and stuff for everyone and no one would be above the law. After some disagreeing and shit the Sith hated this republic and didn't agree with it cause they wanted to rulers and shit. So the Jedi (good guys) join forces with the republic to being democracy to the galaxy.

So after sometime the republic needs soldiers to fight in a war with the sith, so they clone a popular bounty hunter known as jango fett. He's basically like the best bounty hunter there was. So after some agreeing they clone him and basically become the father of a clone that wasn't modified, as regular clones had growth extensions that made him grow at twice the rate or even faster. So the unmodified clone became his son, Boba, has the regular clones went to fight in a war.

So after some fights and disagreements Jango leaves the cloning facility and escapes on a ship with Boba. However the republic had enough time to gather enough DNA to keep cloning him. Jango then went to side with the sith as he was hired since he was a bounty hunter. So the jedi find out of this and go track him down. One Jedi, Obi-wan, gets captured and needs to be rescued. So Anakin tries to find him but ends up getting captured too and the jedi order finds out about this. They then decide to launch a full on attack with the clones they just created. So dozens of other Jedi and tons of clones come out of LAATs, which are basically planes, and kill the sith and battle droids. (Battle droids are just robots that suck at their jobs and gets destroyed by clones)

So years later the war is still going on and the republic is winning cause how superior the clones are and how many the clones can kill. However turns out the supreme chancellor is a sith, so before the entire Jedi order founds out, the supreme chancellor executes order 66, which makes the clones betray the jedi mid-battle and ends up killing most of them. The supreme chancellor convinces Anakin to join the dark side and becomes Darth Vader. Darth Vader then leads the 501st, his clone trooper battalion, to attack the jedi temple.

After a long fight Darth Vader and clones end up winning and killing the rest of the jedi, however some did escape but very few. The rise of the empire then starts and focuses on killing the jedi. With the years continuing on the clones end up dying out and can't be cloned anymore since the original DNA is weakened over the years. The empires gets word of this and ends up destroying the cloning facilities and start recruiting humans.

**Comment by gedehari** [comment]
I forgot the plot but this looks like a solid review, especially when you typed this yourself.
Unfortunately this isn't an issue, so I'll close this.
