### ISSUE TITLE
No gameplay

### ISSUE THREAD

**Issue by Alittletrolling** [gedehari/Funkin-IzzyEngine#2]
There be no gameplay :(

**Comment by gedehari** [comment]
You know what? I think I should make a roadmap to track my progresses. Putting it in README.md sounds like a good idea. Anyways, this issue will stay open until gameplay implemented. Thanks.

**Comment by Alittletrolling** [comment]
good

**Comment by Ashbiord** [comment]
A

Pada tanggal Sen, 21 Jun 2021 08.10, Alittletrolling <
***@***.***> menulis:

**Comment by Alittletrolling** [comment]
i agree

**Comment by flashintv** [comment]
go cuck myself :gachihyper:

**Comment by Alittletrolling** [comment]
mfw when when no gameplay

**Comment by gedehari** [comment]
Partial gameplay has been implemented (just input, no scoring) in eb93138d0256c2d45c45c5ecee68b80da048aa71 . Closing this issue.

**Comment by Alittletrolling** [comment]
thank god
