### ISSUE TITLE
Yes

### ISSUE THREAD

**Issue by kaden-mk** [gedehari/Funkin-IzzyEngine#3]
Yes

**Comment by kaden-mk** [comment]
Yes, very cool boner (I didn't even download it yet :EEESCCKDFUHSDO:

**Comment by kaden-mk** [comment]
It takes 42378924397682493768294786239678967283478269489724897624 years to download pls fix

**Comment by gedehari** [comment]
¯\_(ツ)_/¯ Not an issue, closing.

**Comment by kaden-mk** [comment]
NOOOOOOOOOOOOO
